name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 5:30 AM UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last run: $(date)" > daily-update.txt

      - name: Commit changes (nihal.badiger@gramener.com)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "nihal.badiger@gramener.com"
          git add daily-update.txt
          git commit -m "Daily update: $(date)"
          git push
